def upper_count(text):
    count = 0
    list_text = text.split()
    for i in list_text:
        if i.isupper():
            count+=1
    return count
count = upper_count('THIS is ME')
print(count)

def emoticons(text):
    keys = list(e.keys())
    list_text = text.split()
    n = len(list_text)
    for i in range(n):
        if list_text[i] in keys:
            list_text[i] = e[list_text[i]]
            print(list_text[i])
    text = " ".join(list_text)
    return text
e = {"yay!": "good","yay": "good","yaay": "good","yaaay": "good","yaaaay": "good","yaaaaay": "good",":/": "bad",":&gt;": "sad",":')": "sad",":-(": "frown",
    ":(": "frown",":s": "frown",":-s": "frown","&lt;3": "heart",":d": "smile",":p": "smile",":dd": "smile","8)": "smile",":-)": "smile",":)": "smile",
    ";)": "smile","(-:": "smile","(:": "smile",":/": "worry",":&gt;": "angry",":')": "sad",":-(": "sad",":(": "sad",":s": "sad",":-s": "sad",r"\br\b": "are",
    r"\bu\b": "you",r"\bhaha\b": "ha",r"\bhahaha\b": "ha",r"\bdon't\b": "do not",r"\bdoesn't\b": "does not",r"\bdidn't\b": "did not",r"\bhasn't\b": "has not",r"\bhaven't\b": "have not",r"\bhadn't\b": "had not",
    r"\bwon't\b": "will not",r"\bwouldn't\b": "would not",r"\bcan't\b": "can not",r"\bcannot\b": "can not",r"\bi'm\b": "i am","m": "am","r": "are","u": "you","haha": "ha",
    "hahaha": "ha",
    "don't": "do not",
    "doesn't": "does not",
    "didn't": "did not",
    "hasn't": "has not",
    "haven't": "have not",
    "hadn't": "had not",
    "won't": "will not",
    "wouldn't": "would not",
    "can't": "can not",
    "cannot": "can not",
    "i'm": "i am",
    "m": "am",
    "i'll" : "i will",
    "its" : "it is",
    "it's" : "it is",
    "'s" : "is",
    "that's" : "that is",
    "weren't" : "were not",
}
t = emoticons('its rainy ;)')
print(t)

neg = ['Abysmal','Apathy',
'Atrocious','brutal','cruel',
'Bemoan',
'Cold-hearted',
'Deplorable','Bad','unfortunate',
'Despicable','reprehensible',
'Detrimental','harm','injury',
'Dreadful','fear','dread','terror','Ghastly',
'Grotesque',
'Gruesome','Hard-hearted',
'Insidious',
'Insipid',
'Malicious',
'Monstrous',
'Noxious',
'Offensive',
'Oppressive',
'Pessimistic',
'Prejudice',
'Repulsive',
'Ruthless',
'Sinister',
'Vice',
'Vicious',
'Vile',
'Villainous',
'Vindictive',
'arse',
'arsehole',
'ass',
'asshole',
'badass',
'bastard',
'beaver',
'bitch',
'bollock',
'bollocks',
'boner',
'bugger',
'bullshit',
'bum',
'cock',
'crap',
'creampie',
'cunt',
'dick',
'dickhead',
'dyke',
'fag',
'faggot',
'fart',
'fatass',
'fuck',
'fuck-around',
'fuck-up',
'fucked',
'fucker',
'fucking',
'Greek',
'holy','shit',
'jackass',
'jerk','off',
'kick','ass',
'kick-ass',
'kike',
'kikes',
'nigga',
'nigger',
'piss',
'pissed',
'pissed-soff',
'pizza-nigger',
'semi',
'shit',
'shittier',
'shittiest',
'shitty',
'slope',
'bitch',
'bitches',
'STFU',
'suck',
'tit',
'trap',
'twat',
'wank',
'Alcoholic',
'Amateur',
'Analphabet',
'Anarchist',
'Ape',
'Arse',
'Arselicker',
'Ass',
'Ass','master',
'Ass-kisser',
'Ass-nugget',
'Ass-wipe',
'Asshole',
'Baby',
'Backwoodsman',
'Balls',
'Bandit',
'Barbar',
'Bastard',
'Bastard',
'Beavis',
'Beginner',
'Biest',
'Bitch',
'Blubber','gut',
'Bogeyman',
'Booby',
'Boozer',
'Bozo',
'Brain-fart',
'Brainless',
'Brainy',
'Brontosaurus',
'Brownie',
'Bugger',
'Bugger','silly',
'Bulloks',
'Bum',
'Bum-fucker',
'Butt',
'Buttfucker',
'Butthead',
'Callboy',
'Callgirl',
'Camel',
'Cannibal',
'Cave',
'Chaavanist',
'Chaot',
'Chauvi',
'Cheater',
'Chicken',
'fucker',
'Clit',
'Clown',
'Cock',
'Cockboy',
'Cockfucker',
'Cockroach',
'Coky',
'Con','merchant',
'Con-man',
'Country','bumpkin',
'Cow',
'Creep',
'Creep',
'Cretin',
'Criminal',
'Cunt',
'Cunt','sucker',
'Daywalker',
'Deathlord',
'Derr','brain',
'Desperado',
'Devil',
'Dickhead',
'Dinosaur',
'Disguesting','packet',
'Diz','brain',
'Do-Do',
'Dog',
'Dog','dirty',
'Dogshit',
'Donkey',
'Drakula',
'Dreamer',
'Drinker',
'Drunkard',
'Dufus',
'Dulles',
'Dumbo',
'Dummy',
'Dumpy',
'Egoist',
'Eunuch',
'Exhibitionist',
'Fake',
'Fanny',
'Farmer',
'Fart',
'Fart','shitty',
'Fatso',
'Fellow',
'Fibber',
'Fish',
'Fixer',
'Flake',
'Flash','Harry',
'Freak',
'Frog',
'Fuck',
'Fuck','face',
'Fuck','head',
'Fuck','noggin',
'Fucker','Gangster',
'Ghost',
'Goose',
'Gorilla',
'Grouch',
'Grumpy',
'Head','fat',
'Hell','dog',
'Hillbilly',
'Hippie',
'Homo',
'Homosexual',
'Hooligan',
'Horse','fucker',
'Idiot',
'Ignoramus','Jack-ass,Jerk',
'Joker',
'Junkey',
'Killer',
'Lard','face',
'Latchkey','child',
'Learner',
'Liar',
'Looser',
'Lucky',
'Lumpy',
'Luzifer',
'Macho',
'Macker',
'Man','old',
'Minx',
'Missing','link',
'Monkey',
'Monster',
'Motherfucker',
'Mucky','pub',
'Mutant',
'Neanderthal',
'Nerfhearder',
'Nobody',
'Nurd',
'Nuts','numb',
'Oddball',
'Oger',
'Oil','dick',
'Old','fart',
'Orang-Uthan',
'Original',
'Outlaw',
'Pack',
'Pain','ass',
'Pavian',
'Pencil','dick',
'Pervert',
'Pig',
'Piggy-wiggy',
'Pirate',
'Pornofreak',
'Prick',
'Prolet',
'Queer',
'Querulant',
'Rat',
'Rat-fink',
'Reject',
'Retard',
'Riff-Raff',
'Ripper',
'Roboter',
'Rowdy',
'Rufian',
'Sack',
'Sadist',
'Saprophyt',
'Satan',
'Scarab','Schfincter'
'Shark',
'Shit','eater',
'Shithead',
'Simulant',
'Skunk',
'Skuz',
'Slave',
'Sleeze',
'Sleeze',
'Slimer',
'Slimy','bastard',
'Small','pricked',
'Snail',
'Snake',
'Snob',
'Snot',
'Square',
'Stinker',
'Stripper',
'Stunk',
'Swindler',
'Swine',
'eletubby',
'Thief',
'Toilett','cleaner',
'Tussi',
'Typ',
'Unlike',
'Vampir',
'Vandale',
'Varmit',
'Wallflower',
'Wanker',
'Wanker','bloody',
'Weeze',
'Whore',
'Wierdo',
'Wino',
'Witch',
'Womanizer',
'Woody-allen',
'Worm',
'Xena',
'Xenophebe',
'Xenophobe',
'XXX',
'Yak',
'Yeti',
'Zit','face']

b = len(neg)
for i in range(b):
    neg[i] = neg[i].lower()

def count_neg(text):
    count = 0
    text = text.lower()
    text_list = text.split()
    n = len(text_list)
    for i in range(n):
        if text_list[i] in neg:
            count+=1
    return count
c = count_neg('yak yak yak')

print(c)
print('nigger' in neg)

import re
if re.search('\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}','an ip 22.123.23.241'):
    print(True)

